#!/usr/bin/env bash
set -euf -o pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -yq --no-install-recommends wget
apt-get update
apt-get dist-upgrade -yq

apt-get install -yq --no-install-recommends \
        emacs24-nox \
        build-essential autotools-dev autoconf automake libtool gettext \
        cpio squashfs-tools \
        git \
        curl ca-certificates \
        gawk alien fakeroot zlib1g-dev uuid-dev libattr1-dev libblkid-dev libselinux-dev libudev-dev libdevmapper-dev parted lsscsi ksh

# Last line is for ZFS build, but most of these things are probably useful elsewhere, too.

apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/*
