#!/usr/bin/env bash
set -euf -o pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -yq --no-install-recommends wget
apt-get update
apt-get dist-upgrade -yq

apt-get install -yq --no-install-recommends \
        emacs24-nox \
        build-essential autotools-dev autoconf automake libtool gettext \
        cpio squashfs-tools \
        git

apt-get autoremove -y
apt-get clean
rm -rf /var/lib/apt/lists/*
